<?php

return array (
  'axiomus' => true,
  'orderStatus' => true,
  'jivo' => true,
  'ymproductreviews' => true,
  'reportdetailed' => true,
  'qvisibility' => true,
  'yandexmarket' => true,
  'referrals' => true,
  'categoryimage' => true,
  'lostproducts' => true,
  'flexdiscount' => true,
  'gdeposylka' => true,
  'metakeywords' => true,
  'rh' => true,
  'fastdeleteimages' => true,
  'quickeditor' => true,
  'yagoods' => true,
  'prettyurls' => true,
  'manager' => true,
  'error301' => true,
  'watermark' => true,
  'editprice' => true,
  'instantorder' => true,
  'convead' => true,
  'cartsreport' => true,
);
//EOF